# 控制参数
T: 0.03                # 控制周期 (秒)
Np: 30                 # 预测步长
Np_min: 15
Nc: 30                # 控制步长
lookahead: 0

curvature_sensitivity: 30.0   # 曲率对预测步长的影响程度，越大越敏感（建议 30 ~ 80）
window_size: 15        # 预测窗口大小

offset: 15         # 参考速度计算的前后点数
alpha: 15        # 减速幅度 

distance_threshold: 0.3   # 参考点与障碍物的距离阈值
push_strength: 1        # 推力强度

# 控制限制
control_limits:
  v_min: -2          # 最小线速度 (m/s)
  v_max: 2            # 最大线速度 (m/s)
  omega_min: -2      # 最小角速度 (rad/s)
  omega_max: 2     # 最大角速度 (rad/s)
  a_min: -4         # 最小加速度 (m/s^2)
  a_max: 4          # 最大加速度 (m/s^2)
  alpha_min: -4.0    # 最小角加速度 (rad/s^2)
  alpha_max: 4.0     # 最大角加速度 (rad/s^2)
  alpha: 10.0         # 曲率敏感度（越大越敏感）

# MPC权重参数
weights:
  x: 1000.0              # x位置跟踪权重
  y: 1000.0              # y位置跟踪权重
  phi: 100.0             # 方向角跟踪权重
  v: 1                   # 控制输入权重
  omega: 0.1
  v_ref: 100.0        # 弯道速度
  obs: 0.2             # 障碍物减速权重

sigma: 1                  # 障碍物惩罚系数 越小越敏感
max_obs: 3            #障碍物减速最大权重
control: true

rush:
  k_v: 10
  k_w: 5
# // 系统动力学方程
# f << dot(x) == v * cos(phi);
# f << dot(y) == v * sin(phi);
# f << dot(phi) == omega;
